# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/quezia/projects/ufjf/inteligComputacional/VRPLTW/HGS-CVRP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/quezia/projects/ufjf/inteligComputacional/VRPLTW/HGS-CVRP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quezia/projects/ufjf/inteligComputacional/VRPLTW/HGS-CVRP/CMakeFiles /home/quezia/projects/ufjf/inteligComputacional/VRPLTW/HGS-CVRP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quezia/projects/ufjf/inteligComputacional/VRPLTW/HGS-CVRP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/quezia/projects/ufjf/inteligComputacional/VRPLTW/HGS-CVRP/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vrpltw

# Build rule for target.
vrpltw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vrpltw
.PHONY : vrpltw

# fast build rule for target.
vrpltw/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/build
.PHONY : vrpltw/fast

src/LocalSearch.o: src/LocalSearch.cpp.o
.PHONY : src/LocalSearch.o

# target to build an object file
src/LocalSearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/LocalSearch.cpp.o
.PHONY : src/LocalSearch.cpp.o

src/LocalSearch.i: src/LocalSearch.cpp.i
.PHONY : src/LocalSearch.i

# target to preprocess a source file
src/LocalSearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/LocalSearch.cpp.i
.PHONY : src/LocalSearch.cpp.i

src/LocalSearch.s: src/LocalSearch.cpp.s
.PHONY : src/LocalSearch.s

# target to generate assembly for a file
src/LocalSearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/LocalSearch.cpp.s
.PHONY : src/LocalSearch.cpp.s

src/Split.o: src/Split.cpp.o
.PHONY : src/Split.o

# target to build an object file
src/Split.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/Split.cpp.o
.PHONY : src/Split.cpp.o

src/Split.i: src/Split.cpp.i
.PHONY : src/Split.i

# target to preprocess a source file
src/Split.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/Split.cpp.i
.PHONY : src/Split.cpp.i

src/Split.s: src/Split.cpp.s
.PHONY : src/Split.s

# target to generate assembly for a file
src/Split.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/Split.cpp.s
.PHONY : src/Split.cpp.s

src/genetic.o: src/genetic.cpp.o
.PHONY : src/genetic.o

# target to build an object file
src/genetic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/genetic.cpp.o
.PHONY : src/genetic.cpp.o

src/genetic.i: src/genetic.cpp.i
.PHONY : src/genetic.i

# target to preprocess a source file
src/genetic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/genetic.cpp.i
.PHONY : src/genetic.cpp.i

src/genetic.s: src/genetic.cpp.s
.PHONY : src/genetic.s

# target to generate assembly for a file
src/genetic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/genetic.cpp.s
.PHONY : src/genetic.cpp.s

src/instance.o: src/instance.cpp.o
.PHONY : src/instance.o

# target to build an object file
src/instance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/instance.cpp.o
.PHONY : src/instance.cpp.o

src/instance.i: src/instance.cpp.i
.PHONY : src/instance.i

# target to preprocess a source file
src/instance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/instance.cpp.i
.PHONY : src/instance.cpp.i

src/instance.s: src/instance.cpp.s
.PHONY : src/instance.s

# target to generate assembly for a file
src/instance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/instance.cpp.s
.PHONY : src/instance.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrpltw.dir/build.make CMakeFiles/vrpltw.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vrpltw"
	@echo "... src/LocalSearch.o"
	@echo "... src/LocalSearch.i"
	@echo "... src/LocalSearch.s"
	@echo "... src/Split.o"
	@echo "... src/Split.i"
	@echo "... src/Split.s"
	@echo "... src/genetic.o"
	@echo "... src/genetic.i"
	@echo "... src/genetic.s"
	@echo "... src/instance.o"
	@echo "... src/instance.i"
	@echo "... src/instance.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/quezia/projects/ufjf/inteligComputacional/VRPLTW/HGS-CVRP/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

